/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/e2e-harness': RouteRecordInfo<'/e2e-harness', '/e2e-harness', Record<never, never>, Record<never, never>>,
    '/features': RouteRecordInfo<'/features', '/features', Record<never, never>, Record<never, never>>,
    '/performance': RouteRecordInfo<'/performance', '/performance', Record<never, never>, Record<never, never>>,
    '/small-example': RouteRecordInfo<'/small-example', '/small-example', Record<never, never>, Record<never, never>>,
  }
}
